### ISSUE TITLE
Find link to `bib` file and import it

### ISSUE THREAD

**Issue by koppor** [JabRef/JabFox#10]
When I visit https://www.uni-bamberg.de/pi/bereich/forschung/publikationen/13-03-lenhard-wirtz/, there is a link "Bibtex" opened, which points to https://www.uni-bamberg.de/fileadmin/uni/fakultaeten/wiai_lehrstuehle/praktische_informatik/Dateien/Publikationen/BibTex/lenhard2013seke.bib.

The Jabref-FirefoxAddon should be able to parse the HTML and find out that a bib is linked. If such a thing is found, that bib should be imported into JabRef when clicking "JR".

Due to https://github.com/tobiasdiez/Jabref-FirefoxAddon/issues/9#issuecomment-161961024 I am aware that there is no Zotero crawler defined for uni-bamberg.de, but do I really have to implement one? If yes, could the Jabref-FirefoxAddon provide a link to a how-to if no crawler is available?

The reason for the request is that there are many more ore less private or university-driven web pages out there offering BibTeX and that they are not registered at Zotero. My current feeling is that the write-Zetero-crawler-for-each-web-page-with-bib-files-one-discoveres-and-pull-that-to-zotero-loop causes more overhead than the Jabref-FirefoxAddon could imply parse the page. Other solution suggestions welcome. Maybe a generic Zotero Crawler?

Refs #9

**Comment by tobiasdiez** [comment]
A generic Zotero Crawler looking for links to bib files should be an option. Good suggestion.

**Comment by tobiasdiez** [comment]
Thinking again about the situation you described: if the website contains a link to a bib file, then we don't need an addon at all, do we? Just clicking the link should open a window asking how you want to open the file and you can choose JabRef there. Afterwards every link to a bib file is automatically opened by JabRef. So no addon needed.

(Moreover, a general zotero crawler also has to handle the case of multiple bib file etc. )
