### ISSUE TITLE
When a DOI link is clicked, it should be fetched via JabRef

### ISSUE THREAD

**Issue by koppor** [JabRef/JabFox#2]
When I have a publishers page opened, e.g., http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=7133510 and I click on the DOI link (e.g., http://dx.doi.org/10.1109/SOSE.2015.22), the URL should *not* open, but the "DOI to BibTeX" fetcher of JabRef called.

I know that one could also download the bib at the publisher, but the DOI import of JabRef just works perfect, why not reusing that?

**Comment by tobiasdiez** [comment]
Mhhh... I think always opening a doi with JabRef is also not desired. So the only possibility would be to add a context menu item. But I don't like this too much since it destroys the simplicity of the one-button-to-rule-them-all-concept.
