### ISSUE TITLE
On Linux, nothing happens with JabRef-3.3.jar

### ISSUE THREAD

**Issue by dbitouze** [JabRef/JabFox#20]
Hi,

many thanks for this module!

Here on Linux, nothing happens with `JabRef-3.3.jar`, despite:

- remote operation is enabled (port 6050) in `JabRef`,
- the path to the `JabRef-3.3.jar` is adjusted in the add-on settings.

Maybe the trouble comes from the fact, on Linux we haven't any executable `JabRef.exe`, only `.jar` files. In such case, the manual should specify this module works only on Windows.

**Comment by tobiasdiez** [comment]
Thanks for reporting this issue.

Which version of Java are you using (run java --version in a terminal)? It seems like there is a problem with java version 1.7 but it works for 1.8, see #19. 
Probably the script provided in https://github.com/JabRef/JabFox/issues/19#issue-138304803 is a workaround.

**Comment by dbitouze** [comment]
> Thanks for reporting this issue.

You're welcome!

> Which version of Java are you using [...]?
```
$ java -version
openjdk version "1.8.0_77"
OpenJDK Runtime Environment (build 1.8.0_77-b03)
OpenJDK Server VM (build 25.77-b03, mixed mode)
```
> It seems like there is a problem with java version 1.7 but it works for 1.8,

Not all 1.8 versions, I'm afraid :)

> see #19.

Ooops, sorry to have miss it!

>Probably the script provided in #19 (comment) is a workaround. 

Now, it works like a charm! Thanks.
