### ISSUE TITLE
Store PDFs according to Jabref settings instead of Zotero

### ISSUE THREAD

**Issue by RKBK** [JabRef/JabFox#22]
I have a system of storing the pdfs associated with my bib file according to settings in Jabref (master folder, naming scheme). Previously, I've been using the LocalCopy addon (http://www.lhnr.de/ext/localcopy/) to download PDFs, which automatically renamed them and placed them in the right folder. 

Is there any way to use JabFox in a similar way, i.e. immediately after downloading the pdf to the Zotero folder, move it over to the folder set in Jabref, and renaming it according to the rules set in Jabref?

**Comment by tobiasdiez** [comment]
There is some built-in functionality in JabRef which covers this case. Under Quality -> Cleanup entries you find the option "Move linked files to default file directory". So just run the cleanup after you imported some entries with JabFox and the files should be moved to the correct directory. 
We plan to add the ability to automatize the last step, i.e. run the cleanup automatically after every import, see #1283.

**Comment by RKBK** [comment]
Great, thanks for the explanation!
