### ISSUE TITLE
Option to not save snapshot link in JabRef?

### ISSUE THREAD

**Issue by RKBK** [JabRef/JabFox#23]
Is there any way to prevent JabFox from storing a link to the Zotero snapshot? I have no need for an html file of the publication web site.

The actual issue I'm trying to solve is the cleanup of items imported from Zotero. I always get both the PDF and the snapshot link. After running the automatic cleanup, the PDF is placed second in the list of document links (I assume the cleanup first deletes the file link, moves the file, and then adds a new file link last in the list). This means that after running cleanup, pressing the PDF icon opens the snapshot HTML file, and not the PDF, requiring me either to manually reorder the two items, or delete the snapshot. If the PDF was the only file link from the start, this would not be a irritating small issue.

**Comment by tobiasdiez** [comment]
Yes it is possible to prevent the creation of the snapshot: under the "General" tab of the **Zotero** preferences you can disable the option "Automatically take snapshots...".
