### ISSUE TITLE
Jabfox import places Journal name and year in BibLaTeX fields Date and Journaltitle, not in bibtex fields

### ISSUE THREAD

**Issue by RKBK** [JabRef/JabFox#24]
When importing an entry using JabFox and Jabref in Bibtex mode, the Journal and year fields are empty. I suppose that this is because JabFox fills in the Date and the Journaltitle fields instead, leaving the necessary Journal and Year entries empty. This means that I have to correct the entry by copying or adding the data to the right fields.

**Comment by tobiasdiez** [comment]
Yes, the reason is that JabFox exports to BibLaTeX format and not the old BibTeX. Thus this issue is a duplicate of #7.
