### ISSUE TITLE
JabFox imports incomplete references into JabRef

### ISSUE THREAD

**Issue by SteveHod** [JabRef/JabFox#29]
I have the JabFox plugin for Firefox, together with JabRef on my computer running Ubuntu 16.04. When I try importing a reference from PubMed some of the information (that's actually important) such as year journal and page numbers is missing. I get the title, abstract and page numbers!

Is there a way for me to select what information JabFox captures? I have previously used the Zotero plugin for Firefox together with BibDesk and this was not a problem and I see that JabFox uses elements of Zotero to capture information.

**Comment by tobiasdiez** [comment]
Can you please send me a link to an article for which the import is not working since I couldn't replicate the problem? For example, importing http://www.ncbi.nlm.nih.gov/pubmed/27382405 gives
````
  pages =         {3428370},
  date =          {2016},
  journaltitle =  {Evidence-Based Complementary and Alternative Medicine: {eCAM}},

````

**Comment by SteveHod** [comment]
sure: [this one] (http://www.ncbi.nlm.nih.gov/pubmed/25547421?dopt=Abstract) for example gives me the authors, title, volume and pages, but not the journal (although this set in JabRef). Probably something that I have not set up properly in JabRef, but not sure what that could be.

**Comment by SteveHod** [comment]
was closed in error.

**Comment by tobiasdiez** [comment]
Yes it is exported in the BibLaTeX format `journaltitle =  {Psychotherapy and Psychosomatics},` and not in the old BibTeX `journal` field. Since version 1.1. of JabFox you can specify in the options that entries should be exported in BibTeX format, afterwards the journal should be present in the `journal` field.

**Comment by SteveHod** [comment]
OK. I have toggled JabRef to BiblaTeX mode and I get the journal title now. 

Interestingly, whilst the BibTeX source shows the correct JournalTitle field, it also has the year written into the Date field. I can change this manually for each entry, but even where the Customize entry types (Required fields) only contains year, I still get year as date.

**Comment by tobiasdiez** [comment]
Yes, in BibLaTeX mode the fields `journaltitle` and `date` are used opposed to `journal` and `year/month`. As I said above, you can change the export mode also for JabFox (Addons -> JabFox -> Options) if you want to stick to BibTeX.

As the issue seems to be fixed, I'll close it now.
