### ISSUE TITLE
Integrate Zotero directly

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/JabFox#31]
so that Zotero does not need to be installed separately. 

Similar to:
https://github.com/zotero/zotero-connectors/tree/master/src

Also change license and add license file
https://github.com/zotero/zotero/blob/685954a487b289277d3acf0ad97c5e6fa45c44fa/COPYING

**Comment by jdpipe** [comment]
Would be great to see this feature added :+1:

**Comment by tobiasdiez** [comment]
This is now implemented.
