### ISSUE TITLE
Clarify that 'Zotero 4.0 for Firefox' is required

### ISSUE THREAD

**Issue by phillipkent** [JabRef/JabFox#39]
Please alter the instructions to clarify that the Zotero version required is 'Zotero 4.0 for Firefox', because the default Zotero download [https://www.zotero.org/download] is version 5 which (I think) does not work with JabFox.

**Comment by khalid-hussain** [comment]
This helped my solve the issue as found in #26.

**Comment by tobiasdiez** [comment]
Thanks for the notification. I completely missed that they already released Zotero 5.
