### ISSUE TITLE
JabRef greyed out on all websites

### ISSUE THREAD

**Issue by Beatzekatze** [JabRef/JabFox#42]
Hi, probably its my stupidity that prevents me from finding the issue. But, well, I need help in figuring it out. I have Zotero installed (Plug in and Stand-alone), JabRef and JabFox installed and configured (the script variant). But on most websites JabRef button is greyed out. There are no related error messages in the console... Any suggestions on how to find clues what is going on there?
(I am using Firefox ESR 52.4.1 (64-bit) on Mac 10. 11)

**Comment by tobiasdiez** [comment]
Do you have installed the old [Zotero 4.0](https://download.zotero.org/extension/zotero-4.0.29.21.xpi) and not the new "Zotero connector"?

**Comment by Beatzekatze** [comment]
Yes, I followed the link in the description. So its 4.0

**Comment by tobiasdiez** [comment]
Ok, that sounds like there is a problem with the Zotero integration / setup of Zotero. Can you import references in Zotero directly (i.e. without using JabFox at all)? I plan to release an update to JabFox in the near future that already integrates all the necessary Zotero code and runs also in the most recent Firefox versions. This should then also solve your problem. But it will take a while until the code is finished.

**Comment by Beatzekatze** [comment]
Sorry for the lat reply. You right, Zotero doesn't work either. Says its outdated:
> This Zotero database requires Zotero 5.0.16 or later.
> Current version: 4.0.29.23
> Please upgrade to the latest version from zotero.org.
Good, I can wait (using Google Scholar Bibtex export atm.)
Thanks for the help and the work :)
