### ISSUE TITLE
Add check for java version

### ISSUE THREAD

**Issue by Kinxkinx** [JabRef/JabFox#52]
When I try to import a citation, there is a message "send to jabref..." that least but nothing is imported, and no jabref wndows is opened. I have this message in the console : 

Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  background.js:12819

**Comment by tobiasdiez** [comment]
This sounds similar to https://github.com/JabRef/JabFox/issues/50. Did you double-check that the the setup is correct according to the steps outlined in the readme?

**Comment by Kinxkinx** [comment]
Yes, double-check... There is also a message in the add-on options : connection status : Testing connection.

**Comment by Kinxkinx** [comment]
The messages during import-fail : 


JabFox: Popup opened  progressPanel.js:10:2
Messaging: Received message: undefined, undefined  messaging.js:53:3
JabFox: Popup opened confirmed  background.js:121:3
TypeError: messageName is undefined at moz-extension://49e8813a-15d3-4691-84ba-c98b842e0f45/Zotero/messaging.js:63  zotero.js:284:4
JabFox: Start translation for tab  Object { id: 7, index: 4, windowId: 3, highlighted: true, active: true, pinned: false, status: "complete", hidden: false, discarded: false, incognito: false, 11 de plus… }  background.js:130:5
reflow : 0.18ms
"Messaging: Received message: Debug.log, translate message received in injected page https://www.cairn.info/revue-francaise-de-gestion-2005-1-page-75.html,"  messaging.js:53:3
"(3)(+0047468): translate message received in injected page https://www.cairn.info/revue-francaise-de-gestion-2005-1-page-75.html"  debug.js:171:5
Messaging: Received message: Prefs.getAsync, firstSaveToServer  messaging.js:53:3
Messaging: Received message: Connector.checkIsOnline,   messaging.js:53:3
Messaging: Received message: Messaging.sendMessage, progressWindow.show,  messaging.js:53:3
Messaging: Received message: Debug.log, Translate: Parsing code for Cairn.info (f46cc903-c447-47d6-a2cf-c75ed22dc96b, 2017-11-13 19:50:00),4  messaging.js:53:3
(4)(+0000073): Translate: Parsing code for Cairn.info (f46cc903-c447-47d6-a2cf-c75ed22dc96b, 2017-11-13 19:50:00)  debug.js:171:5
Messaging: Received message: undefined, undefined  messaging.js:53:3
TypeError: messageName is undefined at moz-extension://49e8813a-15d3-4691-84ba-c98b842e0f45/Zotero/messaging.js:63  zotero.js:284:4
"Messaging: Received message: Debug.log, progressWindow.show message received in injected page https://www.cairn.info/revue-francaise-de-gestion-2005-1-page-75.html,"  messaging.js:53:3
"(3)(+0000008): progressWindow.show message received in injected page https://www.cairn.info/revue-francaise-de-gestion-2005-1-page-75.html"  debug.js:171:5
Messaging: Received message: Connector.callMethod, getSelectedCollection,[object Object]  messaging.js:53:3
JabFox: Tried to contact Zotero standalone: getSelectedCollection  connector.js:3:3
Error: Zotero Offline at moz-extension://49e8813a-15d3-4691-84ba-c98b842e0f45/connector.js:4  zotero.js:284:4
JabFox: code executed  background.js:87:14
Messaging: Received message: Debug.log, Translate: Beginning translation with Cairn.info,  messaging.js:53:3
(3)(+0000008): Translate: Beginning translation with Cairn.info  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Creating translate instance of type web in sandbox,  messaging.js:53:3
(3)(+0000002): Translate: Creating translate instance of type web in sandbox  debug.js:171:5
Messaging: Received message: Debug.log, Translate: translate() now takes an object -- update your code,2  messaging.js:53:3
(2)(+0000049): Translate: translate() now takes an object -- update your code  debug.js:171:5
Messaging: Received message: Translators.get, 951c027d-74ac-47d4-a107-9c3069ab7b48  messaging.js:53:3
"Messaging: Received message: Debug.log, Translate: Binding sandbox to https://www.cairn.info/revue-francaise-de-gestion-2005-1-page-75.html,4"  messaging.js:53:3
"(4)(+0000011): Translate: Binding sandbox to https://www.cairn.info/revue-francaise-de-gestion-2005-1-page-75.html"  debug.js:171:5
Messaging: Received message: undefined, undefined  messaging.js:53:3
TypeError: messageName is undefined at moz-extension://49e8813a-15d3-4691-84ba-c98b842e0f45/Zotero/messaging.js:63  zotero.js:284:4
Messaging: Received message: Debug.log, Translate: Parsing code for Embedded Metadata (951c027d-74ac-47d4-a107-9c3069ab7b48, 2018-02-13 19:40:00),4  messaging.js:53:3
(4)(+0000003): Translate: Parsing code for Embedded Metadata (951c027d-74ac-47d4-a107-9c3069ab7b48, 2018-02-13 19:40:00)  debug.js:171:5
Messaging: Received message: undefined, undefined  messaging.js:53:3
TypeError: messageName is undefined at moz-extension://49e8813a-15d3-4691-84ba-c98b842e0f45/Zotero/messaging.js:63  zotero.js:284:4
JabFox: code executed background.js:87:14
reflow : 0.14ms
Messaging: Received message: Debug.log, Translate: Beginning translation with Embedded Metadata,  messaging.js:53:3
(3)(+0000015): Translate: Beginning translation with Embedded Metadata  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Embedded Metadata: found 84 meta tags.,  messaging.js:53:3
(3)(+0000002): Translate: Embedded Metadata: found 84 meta tags.  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Creating translate instance of type import in sandbox,  messaging.js:53:3
(3)(+0000040): Translate: Creating translate instance of type import in sandbox  debug.js:171:5
Messaging: Received message: Translators.get, 5e3ad958-ac79-463d-812b-a86a9235c28f  messaging.js:53:3
"Messaging: Received message: Debug.log, Translate: Binding sandbox to https://www.cairn.info/revue-francaise-de-gestion-2005-1-page-75.html,4"  messaging.js:53:3
"(4)(+0000009): Translate: Binding sandbox to https://www.cairn.info/revue-francaise-de-gestion-2005-1-page-75.html"  debug.js:171:5
Messaging: Received message: undefined, undefined  messaging.js:53:3
TypeError: messageName is undefined at moz-extension://49e8813a-15d3-4691-84ba-c98b842e0f45/Zotero/messaging.js:63  zotero.js:284:4
Messaging: Received message: Debug.log, Translate: Parsing code for RDF (5e3ad958-ac79-463d-812b-a86a9235c28f, 2018-05-14 12:45:00),4  messaging.js:53:3
(4)(+0000003): Translate: Parsing code for RDF (5e3ad958-ac79-463d-812b-a86a9235c28f, 2018-05-14 12:45:00)  debug.js:171:5
Messaging: Received message: undefined, undefined  messaging.js:53:3
TypeError: messageName is undefined at moz-extension://49e8813a-15d3-4691-84ba-c98b842e0f45/Zotero/messaging.js:63  zotero.js:284:4
JabFox: code executed background.js:87:14
Messaging: Received message: Debug.log, Translate: Initializing RDF data store,  messaging.js:53:3
(3)(+0000015): Translate: Initializing RDF data store  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Promise not available in sandbox in _itemDone(),  messaging.js:53:3
(3)(+0000049): Translate: Promise not available in sandbox in _itemDone()  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Saving item,  messaging.js:53:3
(3)(+0000002): Translate: Saving item  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Running handler 0 for itemDone,5  messaging.js:53:3
(5)(+0000001): Translate: Running handler 0 for itemDone  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Promise not available in sandbox in _itemDone(),  messaging.js:53:3
(3)(+0000002): Translate: Promise not available in sandbox in _itemDone()  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Saving item,  messaging.js:53:3
(3)(+0000002): Translate: Saving item  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Running handler 0 for itemDone,5  messaging.js:53:3
(5)(+0000001): Translate: Running handler 0 for itemDone  debug.js:171:5
"Messaging: Received message: Debug.log, Translate: resolving URL https://www.cairn.info/load_pdf.php?ID_ARTICLE=RFG_154_0075,"  messaging.js:53:3
"(3)(+0000001): Translate: resolving URL https://www.cairn.info/load_pdf.php?ID_ARTICLE=RFG_154_0075"  debug.js:171:5
"Messaging: Received message: Debug.log, Translate: resolved to https://www.cairn.info/load_pdf.php?ID_ARTICLE=RFG_154_0075,"  messaging.js:53:3
"(3)(+0000001): Translate: resolved to https://www.cairn.info/load_pdf.php?ID_ARTICLE=RFG_154_0075"  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Promise not available in sandbox in _itemDone(),  messaging.js:53:3
(3)(+0000001): Translate: Promise not available in sandbox in _itemDone()  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Saving item,  messaging.js:53:3
(3)(+0000001): Translate: Saving item  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Running handler 0 for itemSaving,5  messaging.js:53:3
(5)(+0000002): Translate: Running handler 0 for itemSaving  debug.js:171:5
Messaging: Received message: Messaging.sendMessage, progressWindow.itemSaving,moz-extension://49e8813a-15d3-4691-84ba-c98b842e0f45/images/treeitem-journalArticle.png,Le rôle de l'acteur tiers dans la construction d'un réseau stratégique,vwxOef8K  messaging.js:53:3
Messaging: Received message: Debug.log, Translate: Saving via queue,  messaging.js:53:3
(3)(+0000002): Translate: Saving via queue  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Translation successful,  messaging.js:53:3
(3)(+0000001): Translate: Translation successful  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Running handler 0 for done,5  messaging.js:53:3
(5)(+0000001): Translate: Running handler 0 for done  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Running handler 1 for done,5  messaging.js:53:3
(5)(+0000001): Translate: Running handler 1 for done  debug.js:171:5
Messaging: Received message: Prefs.getAsync, reportTranslationFailure  messaging.js:53:3
Messaging: Received message: Connector.callMethodWithCookies, saveItems,[object Object]  messaging.js:53:3
Messaging: Received message: Prefs.getAsync, reportTranslationFailure  messaging.js:53:3
"Messaging: Received message: Debug.log, progressWindow.itemSaving message received in injected page https://www.cairn.info/revue-francaise-de-gestion-2005-1-page-75.html,"  messaging.js:53:3
"(3)(+0000008): progressWindow.itemSaving message received in injected page https://www.cairn.info/revue-francaise-de-gestion-2005-1-page-75.html"  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Save via Standalone succeeded,  messaging.js:53:3
(3)(+0000005): Translate: Save via Standalone succeeded  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Running handler 0 for itemDone,5  messaging.js:53:3
JabFox: Got task to convert  <unavailable>  to BibTeX  bibtexConverter.js:49:3
(5)(+0000001): Translate: Running handler 0 for itemDone  debug.js:171:5
JabFox: Convert items to BibTeX:  <unavailable>  bibtexConverter.js:2:2
Messaging: Received message: Messaging.sendMessage, progressWindow.itemProgress,moz-extension://49e8813a-15d3-4691-84ba-c98b842e0f45/images/treeitem-journalArticle.png,Le rôle de l'acteur tiers dans la construction d'un réseau stratégique,vwxOef8K,100  messaging.js:53:3
Messaging: Received message: Debug.log, Translate: Running handler 0 for done,5  messaging.js:53:3
(5)(+0000004): Translate: Running handler 0 for done  debug.js:171:5
Messaging: Received message: Messaging.sendMessage, progressWindow.done,true  messaging.js:53:3
Messaging: Received message: Translators.get, 9cb70025-a888-4a29-a210-93ec52da40d4  messaging.js:53:3
"Messaging: Received message: Debug.log, progressWindow.itemProgress message received in injected page https://www.cairn.info/revue-francaise-de-gestion-2005-1-page-75.html,"  messaging.js:53:3
"(3)(+0000009): progressWindow.itemProgress message received in injected page https://www.cairn.info/revue-francaise-de-gestion-2005-1-page-75.html"  debug.js:171:5
"Messaging: Received message: Debug.log, progressWindow.done message received in injected page https://www.cairn.info/revue-francaise-de-gestion-2005-1-page-75.html,"  messaging.js:53:3
"(3)(+0000069): progressWindow.done message received in injected page https://www.cairn.info/revue-francaise-de-gestion-2005-1-page-75.html"  debug.js:171:5
"Messaging: Received message: Debug.log, Translate: Binding sandbox to http://www.example.com/,4"  messaging.js:53:3
"(4)(+0000003): Translate: Binding sandbox to http://www.example.com/"  debug.js:171:5
Messaging: Received message: undefined, undefined  messaging.js:53:3
TypeError: messageName is undefined at moz-extension://49e8813a-15d3-4691-84ba-c98b842e0f45/Zotero/messaging.js:63  zotero.js:284:4
Messaging: Received message: Debug.log, Translate: Parsing code for BibTeX (9cb70025-a888-4a29-a210-93ec52da40d4, 2018-03-04 22:10:00),4  messaging.js:53:3
(4)(+0000003): Translate: Parsing code for BibTeX (9cb70025-a888-4a29-a210-93ec52da40d4, 2018-03-04 22:10:00)  debug.js:171:5
Messaging: Received message: undefined, undefined  messaging.js:53:3
TypeError: messageName is undefined at moz-extension://49e8813a-15d3-4691-84ba-c98b842e0f45/Zotero/messaging.js:63  zotero.js:284:4
JabFox: code executed background.js:87:14
Messaging: Received message: Debug.log, Translate: Beginning translation with BibTeX,  messaging.js:53:3
(3)(+0000044): Translate: Beginning translation with BibTeX  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Got value geindre for %a,  messaging.js:53:3
(3)(+0000002): Translate: Got value geindre for %a  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Got value rôacteur for %t,  messaging.js:53:3
(3)(+0000002): Translate: Got value rôacteur for %t  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Got value 2005 for %y,  messaging.js:53:3
(3)(+0000001): Translate: Got value 2005 for %y  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Translation successful,  messaging.js:53:3
(3)(+0000006): Translate: Translation successful  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Running handler 0 for done,5  messaging.js:53:3
(5)(+0000001): Translate: Running handler 0 for done  debug.js:171:5
Messaging: Received message: Debug.log, Translate: Running handler 1 for done,5  messaging.js:53:3
(5)(+0000002): Translate: Running handler 1 for done  debug.js:171:5
JabFox: Send BibTeX to JabRef:  
@article{geindre_roacteur_2005,
	title = {Le rôle de l'acteur tiers dans la construction d'un réseau stratégique},
	volume = {no 154},
	issn = {0338-4551},
	url = {https://www.cairn.info/revue-francaise-de-gestion-2005-1-page-75.html},
	doi = {10.3166/rfg.154.75-91},
	abstract = {La prise en compte de l’acteur tiers dans la conceptualisation des réseaux stratégiques permet de comprendre le processus de construction de ce type d’organisation. À partir de l’expérience et de l’action d’un syndicat professionnel, nous mettons en évidence le rôle triple de cet acteur tiers dans la mise en place de relation de confiance et de coopération entre entreprises. Le syndicat s’impose, en effet, comme un initiateur des relations, un agent facilitateur de leur développement et un garant du bon fonctionnement du réseau ainsi créé.},
	language = {fr},
	number = {1},
	urldate = {CURRENT\_TIMESTAMP},
	journal = {Revue française de gestion},
	publisher = {Lavoisier},
	author = {Geindre, Sébastien},
	year = {2005},
	pages = {75--91},
	file = {Full Text PDF:https\://www.cairn.info/load_pdf.php?ID_ARTICLE=RFG_154_0075:application/pdf;Snapshot:https\://www.cairn.info/revue-francaise-de-gestion-2005-1-page-75.html:text/html}
}  connector.js:63:3
reflow : 0.09ms

**Comment by tobiasdiez** [comment]
Thanks for the details! However, in the log everything looks fine and there is no message that points to a problem (or even gives a hint about what fails). Firefox is not able to connect to JabRef but also does not say where the problem lies. Sorry, but given these sparse information, there is nothing I can do right now.

**Comment by tobiasdiez** [comment]
@Kinxkinx do you use Windows 7 or 8? In this case, upgrading [Powershell to version 5](https://www.microsoft.com/en-us/download/details.aspx?id=54616) may work.

**Comment by Kinxkinx** [comment]
Windows 7. I have upgraded Powershell. Problem solved ! (many thanks)

**Comment by Kbudidha** [comment]
I have this exact same issue. However, am using windows 10. Also, the connection status shows successfully connected to jabref. Nothing is being imported to jabref.

**Comment by thedarkhunter** [comment]
I had the same issue and fixed installing Java.
https://github.com/JabRef/JabFox/issues/59

**Comment by jpmaterial** [comment]
I had the same issue and fixed it by adding C:\Program Files\Common Files\i4j_jres\1.8.0_172\bin to the PATH (and restarting Firefox).

**Comment by tobiasdiez** [comment]
Since there are many reports about a missing or misconfigured java installation, I think we should add a check that java is installed correctly.

**Comment by tobiasdiez** [comment]
As JabRef 5.0 comes with its own java embedded, there is no need to have this anymore.
