### ISSUE TITLE
Jabfox not available for Firefox 68.0

### ISSUE THREAD

**Issue by amcbedli** [JabRef/JabFox#61]
I've just installed Jabref on my Ubuntu 18.04 computer and wanted to get the Firefox extension, but when I got on the page, it tells me that this extension is not available on my platform. I'm using Firefox 68.0. Is there an update planed or what should I do? Thank you!

![Capture du 2019-07-22 11-30-40](https://user-images.githubusercontent.com/43377895/61622056-598b5c80-ac74-11e9-8277-409bc488d68d.png)

**Comment by tobiasdiez** [comment]
The problem is not Firefox 68 but that JabFox currently does not run on Linux, see https://github.com/JabRef/JabFox/issues/48
