### ISSUE TITLE
Allow export as Bibtex or BibLatex

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/JabFox#7]
Add option to allow export as Bibtex or BibLatex

**Comment by koppor** [comment]
What would be the difference? In my current settings, biblatex perfectly handles bibtex files. Are there fields which need a different naming?

**Comment by tobiasdiez** [comment]
Internally, zotero translators are used to translate the webpage to a zotero item and then to bibtex. There are two different translators (bibtex vs biblatex) for the latter conversion, which result in different output. For more information, see the [discussion in the zotero forum](https://forums.zotero.org/discussion/33750/biblatex-export-versus-bibtex-export/).
