### ISSUE TITLE
postMessage on disconnected port

### ISSUE THREAD

**Issue by Krzmbrzl** [JabRef/JabFox#75]
I just installed JabFox and I have installed JabRef via jabref_5.0.0-1_amd64.deb from https://builds.jabref.org/master/.

However I don't see any additional menu or something like this in Firefox (v70.0 (64-bit)) and when I look into the JabFox preferences, it says 
```
Error: Attempt to postMessage on disconnected port
```
for the connection status.

**Comment by tobiasdiez** [comment]
Could you please make sure that `/usr/lib/mozilla/native-messaging-hosts/` contains `jabref.json` and that this file points to the correct installation folder. Thanks!

**Comment by Krzmbrzl** [comment]
It look like this:
```
{                                                                                                                                                     
  "name": "org.jabref.jabref",                                                                                                                        
  "description": "JabRef",                                                                                                                            
  "path": "/opt/jabref/lib/jabrefHost.py",                                                                                                            
  "type": "stdio",                                                                                                                                    
  "allowed_extensions": [                                                                                                                             
    "@jabfox"                                                                                                                                         
  ]                                                                                                                                                   
}  
```
and `/opt/jabref/lib/jabrefHost.py` does indeed exist. However only root can access it. Could that be the problem?

**Comment by tobiasdiez** [comment]
Can you try and give yourself (i.e the local user) access rights to `/opt/jabref/lib/`. Alternatively, it might work if you run firefox with admin rights. @LyzardKing do you have an idea what went wrong? The same problems appears also on mac: https://github.com/JabRef/JabFox/pull/77

**Comment by LyzardKing** [comment]
The user shouldn't have access to it, so that shouldn't be the problem here..
It's installed in /opt by sudo, so it should be owned by root.
I'll try and install and see what's happening.

**Comment by LyzardKing** [comment]
Changing the permissions is not the right thing to do. It would also break a multi user system.
But I'm not sure what the issue is...It's not working, but it's nothing I changed..
The path is correct, and it should still work.
It's very strange.

**Comment by tobiasdiez** [comment]
Is the python script still marked executable?

**Comment by Krzmbrzl** [comment]
> Alternatively, it might work if you run firefox with admin rights

It appears as if Firefox is very stubborn and won't start with admin rights. Tried a few tricks but still I am unable to start firefox with root privileges.

Okay I seem to have figured out what the problem is: I can get JabFox to work, if I grant execution privileges for `other` to `jabrefHost.py`. Not the before the execution flag wasn't set at all (or maybe it got removed during me messing around with the file's ownership).

I don't know if that is possible during the installation of a firefox addon but my suggestion would be to create a new pseudo-group for the addon, assign this group to all jabFox associated files and grant execution privileges to `group` on the respective files...

**Comment by LyzardKing** [comment]
@tobiasdiez The python script is not set as executable.
That's the solution needed.
I don't know where the regression happened..

**Comment by LyzardKing** [comment]
Testing now to see if it's enough to chmod in the source for both the deb and the snap.
Once I confirm I'll upload a PR

**Comment by LyzardKing** [comment]
@Krzmbrzl  Does the latest build fix the issue?

**Comment by Krzmbrzl** [comment]
I set the permissions manually and it's working now. Didn't try the new build... But if the changed permissions are now included I'd say it should work just fine.

**Comment by diabl0w** [comment]
I am getting really confused and frustrated.... I installed https://aur.archlinux.org/packages/jabref-latest/ and then installed this addon through Mozilla's addon website... is this not the proper way to do it? I have the same message as OP, but the json file does not exist at all rather than just having the wrong permissions
